### ISSUE TITLE
Link to the Pyvec Style guides for Pyvo meetups in README

### ISSUE THREAD

**Issue by apophys** [pyvec/header-image-maker#6]
Each individual meetup uses its own design for Facebook event header (e.g. coat of arms).
Please include the link to the official materials in the README. This repo holds an overlay specific to Brno.

**Comment by honzajavorek** [comment]
See https://github.com/pyvec/resources/tree/master/Design/Pyvo%20Facebook%20Event%20Header. Contributions to README are welcome!
